// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct connection for all Prisma CLI operations (db push, migrate, etc.)
    // PgBouncer (pooled) URL hangs on DDL — use DIRECT_URL here
    url: process.env["DIRECT_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
